name: CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        include:
          - os: ubuntu-latest
            displayName: Ubuntu
          - os: windows-latest
            displayName: Windows

    name: Build on ${{ matrix.displayName }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    env:
      INSTALL_RUN_RUSH_LOCKFILE_PATH: ${{ github.workspace }}/common/config/validation/rush-package-lock.json
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - run: git config --global user.email "spfx-cli-bot@users.noreply.github.com"

      - run: git config --global user.name "SPFx CLI Bot"

      - uses: actions/setup-node@v3
        with:
          node-version: 22.15.0

      - name: Verify Change Logs
        run: node common/scripts/install-run-rush.js change --verify

      - name: Rush Install
        run: node common/scripts/install-run-rush.js install

      - name: Rush test-and-package-solution
        run: node common/scripts/install-run-rush.js test-and-package-solution --production --timeline --verbose
